[build-system]
build-backend = "scikit_build_core.build"
requires = [
    "cython",
    "scikit-build-core",
    "cython-cmake",
    "numpy",
]

[project]
name = "ta_lib_easy"
version = "1.0.4"
requires-python = ">=3.8"
dependencies = [
    "numpy>=1.20",
]

[tool.scikit-build]
ninja.make-fallback = false
build.verbose = true
logging.level = "DEBUG"

[tool.cibuildwheel]
build = "cp*"
build-frontend = "build[uv]"

[dependency-groups]
ci = [
    "cibuildwheel==2.22.0",
    "twine>=5.1.0",
]
